FormMovie/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls', namespace='home'))

]

home/urls.py
from django.urls import path
from . import views

app_name ='home'
urlpatterns = [
    path('index', views.HomeView.as_view(), name='home'),
    path('', views.RegisterMovieView.as_view(), name='movie_register'),
    path('detail/<int:movie_id>/', views.DetailView.as_view(), name= 'details'),
    path('delete/<int:movie_id>/', views.DeleteView.as_view(), name='delete'),
    path('registermovie/data/', views.ajax_data_view, name='movie_register_ajax'),

    path('edit/<int:movie_id>', views.EditView.as_view(), name='edit'),
    path('edit/ajax/', views.ajax_data_edit_view.as_view(), name='edit_ajax_get'),

]

home/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    movie_name = models.CharField(max_length=100)
    director = models.CharField(max_length=100)
    release_date = models.CharField(max_length=100)
    Genre = models.CharField(max_length=100)
    imdb = models.CharField(max_length=100)


class Test(models.Model):
    test_name = models.CharField(max_length=100)
    director = models.CharField(max_length=100)
    release_date = models.IntegerField()
    genre = models.CharField(max_length=100)
    imdb = models.IntegerField()

home/forms.py
from django import forms

from home.models import Movie


class RegisterMovieForm(forms.Form):
    movie_name = forms.CharField(max_length=100)
    director = forms.CharField(max_length=100)
    Release_date = forms.CharField(max_length=100)
    Genre = forms.CharField(max_length=100)
    imdb = forms.CharField(max_length=100)

class MovieUpdateForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'







class RegisterTestForm(forms.Form):
    test_name = forms.CharField(max_length=100)
    director = forms.CharField(max_length=100)
    release_date = forms.IntegerField()
    genre = forms.CharField(max_length=100)
    imdb = forms.IntegerField()

home/views.py
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic.detail import BaseDetailView

from .forms import RegisterMovieForm, MovieUpdateForm
from .models import Movie, Test
from django.contrib import messages
# Create your views here.

import json
from django.core.serializers.json import DjangoJSONEncoder

class HomeView(View):
    def get(self, request):
        all = Movie.objects.all()

        print(Movie.objects.values())
        print('hiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii')

        return render(request, 'home/index.html', {'movies':all})

    def post(self, request):

        return render(request, 'home/index.html')

class RegisterMovieView(View):

    def get(self, request):

        return render(request, 'home/registermovie.html')

    def post(self, request):
        form = RegisterMovieForm(request.POST)
        # print(form.test_name)

        cd = form.data
        # print(cd)
        Movie.objects.create(movie_name=cd['movie_name'],
                            director=cd['director'],
                            release_date=cd['release_date'],
                            Genre=cd['Genre'],
                            imdb=cd['imdb'],
                            )
        return redirect('home:movie_register')



class DetailView(View):

    def get(self, request, movie_id):
            movie = Movie.objects.get(id=movie_id)

            return render(request, 'home/detail.html', {'movie':movie})

class DeleteView(View):

    def get(self, request, movie_id):
            Movie.objects.get(id=movie_id).delete()
            messages.success(request, 'mevie deleted succ')
            return redirect('home:movie_register')


def ajax_data_view(request):
    all = Movie.objects.all().values()
    # data = json.dumps(list(all), cls=DjangoJSONEncoder)
    data = list(all)

    # data = {'message': 'This is data retrieved via AJAX GET request.'}
    # print(data)
    return JsonResponse(data, safe=False)

class ajax_data_edit_view(View):

    def get(self,request):
        print(request.GET)

        movie_id = int(request.GET.get("movie_id"))

        print(movie_id)

        all = Movie.objects.all().values()
        # data = json.dumps(list(all), cls=DjangoJSONEncoder)
        list_data = list(all)
        data = {}
        for item in list_data:
            if movie_id == item['id']:
                data = item
        print(movie_id + 1000000)
        print(data)

        # data = {'message': 'This is data retrieved via AJAX GET request.'}
        # print(data)
        return JsonResponse(data, safe=False)

    def post(self, request):
        print('hiiiiiii Post Ajax')
        # print(movie_id + 300000)
        print(request.POST.get("movie_id"))
        print(request.POST)
        movie_id = int(request.POST.get("movie_id"))
        movie = Movie.objects.get(id=movie_id)

        movie.save()
        print(movie.movie_name)

        form = MovieUpdateForm(request.POST, instance=movie)
        if form.is_valid():
            form.save()

        return redirect('#')




class EditView(View):

    def get(self, request,movie_id):

        # Movie.objects.get(id=movie_id).delete()
        # messages.success(request, 'mevie deleted succ')
        #
        print(movie_id)
        print(movie_id)
        print(movie_id)
        print(movie_id)
        print(movie_id)

        return render(request, 'home/edit.html')


    def post(self, request,movie_id):

        print("post movie id")
        return redirect('home:movie_register')

home/templates/home/detail.html
{% extends 'base.html' %}


{% block content %}
{#<h3> {{ movie.movie_name }} </h3>#}
    <a href="{% url 'home:delete' movie.id %}">Delete</a>

    <h3>{{ movie.movie_name }}</h3>
    <p>{{ movie.director }}</p>
    <p>{{ movie.release_date }}</p>
    <p>{{ movie.Genre }}</p>
    <p>{{ movie.imdb }}</p>

{% endblock %}

home/templates/home/edit.html
{% extends 'base.html' %}


{% block content %}

    {% load static %}
    <link href="{% static 'styles.css' %}" rel="stylesheet" />



  	<div id="container">

	    <div id="book-list">
	    	<h2 class="title">ویرایش فیلم ها </h2>

			<div class="clear"></div>

            <table>
                <tbody>
                </tbody>

            </table>
	    </div>

         <form id="add-book" action="" method="post" >
        {% csrf_token %}
{#        {{  form.as_p }}#}

        <p><label for="id_subject">نام</label>
            <input id="movie_name" value="test" type="text" name="movie_name" maxlength="100" required></p>
        <p><label for="id_subject">کارگردان</label>
            <input id="director" type="text" name="director" maxlength="100" required></p>
        <p><label for="id_subject">سال ساخت</label>
            <input id="release_date" type="text" name="release_date" maxlength="100" required></p>
        <p><label for="id_subject">ژانر</label>
            <input id="Genre" type="text" name="Genre" maxlength="100" required></p>
        <p><label for="id_subject">نمره imdb </label>
            <input id="imdb" type="text" name="imdb" maxlength="100" required></p>

        <input class="button" onclick="StartAjax()" type="submit" value="ثبت">
    </form>

    </div>


 <script src="{% static 'edit1.js' %}"></script>
{% endblock %}

home/templates/home/index.html
{% extends 'base.html' %}

{% block content %}
{#{{ movies }}#}
    {% for movie in movies  %}

        <a href="{% url 'home:details' movie.id %}"> {{ movie.movie_name }}</a><br/>

    {% endfor %}



{% endblock %}

home/templates/home/registermovie.html
{% extends 'base.html' %}


{% block content %}

    {% load static %}
    <link href="{% static 'styles.css' %}" rel="stylesheet" />



  	<div id="container">

	    <div id="book-list">
	    	<h2 class="title"> فیلم ها </h2>

			<div class="clear"></div>

            <table>
                <tbody>
                </tbody>

            </table>
	    </div>

         <form id="add-book" action="" method="post" >
        {% csrf_token %}
{#        {{  form.as_p }}#}

        <p><label for="id_subject">نام</label>
            <input id="movie_name" type="text" name="movie_name" maxlength="100" required></p>
        <p><label for="id_subject">کارگردان</label>
            <input id="director" type="text" name="director" maxlength="100" required></p>
        <p><label for="id_subject">سال ساخت</label>
            <input id="release_date" type="text" name="release_date" maxlength="100" required></p>
        <p><label for="id_subject">ژانر</label>
            <input id="Genre" type="text" name="Genre" maxlength="100" required></p>
        <p><label for="id_subject">نمره imdb </label>
            <input id="imdb" type="text" name="imdb" maxlength="100" required></p>

        <input class="button"  type="submit" value="ثبت">
    </form>

    </div>


 <script src="{% static 'movie_javascript.js' %}"></script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>




<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>

{#<script> src="javascript.js" </script>#}

    <meta charset="UTF-8">
    <title>Movie</title>

    <style>

    </style>

    
</head>
<body>

    {% include 'messages.html' %}
    {%  block content  %} {% endblock %}





</body>
</html>

templates/messages.html
{% if messages %}

    {% for msg in messages %}

    <p>{{ msg }}</p>

    {% endfor %}

{% endif %}